//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(UsdHoudiniHoudiniLayerInfo);
TF_WRAP(UsdHoudiniHoudiniFieldAsset);
TF_WRAP(UsdHoudiniHoudiniMetaCurves);
TF_WRAP(UsdHoudiniHoudiniEditableAPI);
TF_WRAP(UsdHoudiniHoudiniSelectableAPI);
TF_WRAP(UsdHoudiniHoudiniViewportGuideAPI);
TF_WRAP(UsdHoudiniHoudiniCameraPlateAPI);
TF_WRAP(UsdHoudiniHoudiniProceduralAPI);
TF_WRAP(UsdHoudiniHoudiniViewportLightAPI);
TF_WRAP(UsdHoudiniTokens);
